### ISSUE TITLE
DJI DroneID frames & burst generation and demodulation test

### ISSUE THREAD

**Issue by Retinaaa** [proto17/dji_droneid#9]
Hi there,
Very interesting work and write-up. I'd love to test [proto17](https://github.com/proto17) /[dji_droneid](https://github.com/proto17/dji_droneid)
First, I generated the frames with the appropriate hypothetical data and generated the DJI DroneID burst.

Then I gave that signal to the file `process_file.m`
But even though the correlation levels in matlab/octave is greater than 0.7, the following error was reported
I either get:
![Screenshot from 2022-06-14 16-50-50](https://user-images.githubusercontent.com/106088840/173834285-89e835fe-2098-4462-8ab3-6cf536ae10f6.png)

Is the issue with running the bursts through MATLAB is that some amount of padding either side of the burst is required in order to do some of the operations. , or have I configured something incorrectly?

Thanks for all your work, very interesting repo!

**Comment by proto17** [comment]
Glad to see you're getting good samples out!  The issue you're seeing is that the `process_file.m` script wants a little bit of padding to the left and right of the burst.  The `extract_bursts_from_file` function is provided a number of samples worth of padding that it should extract which is applied to the beginning and end of the burst [1].  [2] is where I set the padding to be the filter length so that I have enough samples at both ends to prevent the low pass filter from messing up the important samples.  So, if you want to run the burst back through `process_file.m` you need to add some noise or just zeros to the beginning and end of the burst.

[1] https://github.com/proto17/dji_droneid/blob/main/matlab/updated_scripts/extract_bursts_from_file.m#L23
[2] https://github.com/proto17/dji_droneid/blob/main/matlab/updated_scripts/process_file.m#L51

**Comment by Retinaaa** [comment]
The padding worked, Thanks once again for your great work!
